[package]
name = "jagger"
version = "0.0.1"
authors = ["Trent Clarke <trent.clarke@gmail.com>"]

[[bin]]
name = "jagger"

[dependencies]
log = "0.2.5"
getopts = "0.2.4"
time = "0.1.20"
#env_logger = "0.2.5"
